pr: none 
trigger: none

stages:
- stage: test
  displayName: Run integration test fior Pre-prod
  jobs:
  - job: pre_integration_test
    displayName: pre_integration_test
    timeoutInMinutes: 150
    strategy:
      maxParallel: 1
    steps:
      - task: DownloadSecureFile@1
        name: testSecrets
        displayName: Download testSecrets json
        inputs:
          secureFile: 'Test_Secret.json'
      
      - task: CmdLine@2
        displayName: Copy the secure files to git repository
        inputs:
          script: |
            cp $(testSecrets.secureFilePath) .
      
      - script: |
          #rm -rf ~/.m2/repository
          if ! [ -x /usr/bin/javac ]; then
            sudo apt install -y openjdk-11-jdk-headless
          fi
          export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          ulimit -s 524288
          ulimit -u 524288
          ulimit -a
          export MAVEN_OPTS="-Xmx512m"
          #export MAVEN_OPTS=-Xmx256m -XX:MaxPermSize=512m
          export _JAVA_OPTIONS="-Xmx512m"
          java -XX:+PrintFlagsFinal -Xms512m -Xmx1024m -Xss50M -XX:VMThreadStackSize=50m -XX:CompilerThreadStackSize=50M -version | grep -iE 'HeapSize|PermSize|ThreadStackSize'
          echo "stack size definition complete"
          echo cat /proc/sys/kernel/threads-max
          cat /proc/sys/kernel/threads-max
          chmod 666 /proc/sys/kernel/threads-max
          echo 100000 > /proc/sys/kernel/threads-max
          echo "threads-max set to 100k"
          mvn -version
          mvn clean
          #mvn test -Dtest=TestRunnerParallel -Dkarate.env="preprod"
          #mvn test-compile -e -DbaseURL=https://apimpre.ntuc.org.sg/api/ gatling:test
          #mvn test-compile -Dkarate.env="preprod" gatling:test
          #mvn test-compile -DbaseURL=https://apimpre.ntuc.org.sg/api/ gatling:test -Dgatling.simulationClass=ntuc_memberportal.LoadSimulation_dealservice
          #mvn test-compile -DbaseURL=https://apimpre.ntuc.org.sg/api/ gatling:test -Dgatling.simulationClass=ntuc_memberportal.LoadSimulation_paymentservice
          #mvn test-compile -DbaseURL=https://apimpre.ntuc.org.sg/api/ gatling:test -Dgatling.simulationClass=ntuc_memberportal.LoadSimulation_notificationservice
          #mvn test-compile -DbaseURL=https://apimpre.ntuc.org.sg/api/ gatling:test -Dgatling.simulationClass=ntuc_memberportal.LoadSimulation_memberservice
          mvn test-compile -DbaseURL=https://apimpre.ntuc.org.sg/api/ gatling:test -Dgatling.simulationClass=ntuc_memberportal.LoadSimulation_userservice
        displayName: mvn testcreating
        continueOnError: true
      - publish: $(System.DefaultWorkingDirectory)/target
        artifact: integration_test_reports
